### ISSUE TITLE
Migrate to Postgres

### ISSUE THREAD

**Issue by kochman** [wtg/shuttletracker#103]
We're going to move from MongoDB to Postgres. A lot of our data is relational (e.g. updates reference vehicles, stops reference routes) and Postgres has nice LISTEN/NOTIFY commands that will be very useful for #58 and save us from having to bring in another dependency like Redis.

Things we have to do for this:
- [x] Turn `database` into an interface instead of just a MongoDB implementation
- [x] Write a MongoDB implementation of the `database` interface
- [ ] Write a Postgres implementation of the `database` interface
- [ ] Write a migrator that will move our data. Potentially a JSON importer and exporter that doesn't care about the underlying database. (This would also aid in getting new contributors set up.)
- [ ] Update documentation

**Comment by kochman** [comment]
Database interface in progress in #104.

**Comment by jlyon1** [comment]
The interface needs to support the reordering of stops

**Comment by kochman** [comment]
I am not planning to work on this at the moment, but it would still be great to do.
