### ISSUE TITLE
Enhancement to night mode

### ISSUE THREAD

**Issue by galengold** [wtg/shuttletracker#127]
In issue #92, night mode was suggested. I think that this could be enhanced by using a cookie or something to remember if night mode was enabled.

**Comment by kochman** [comment]
Great idea. I think we'd probably want to do this with localStorage so we don't have to send it to the server on each request.

**Comment by galengold** [comment]
If you don't mind, I'd like to take a crack at this this weekend.

**Comment by kochman** [comment]
Definitely, it's all yours!

**Comment by galengold** [comment]
How do you run the application locally? I haven't used Go before. The instructions in README.md are for getting the latest version from the main repo's master branch, and from my reading `go get` doesn't work for getting certain branches/revisions/tags.

**Comment by jlyon1** [comment]
Fixed by #128
