### ISSUE TITLE
Admin statistics page

### ISSUE THREAD

**Issue by kochman** [wtg/shuttletracker#155]
Some potentially interesting things to report on:

- Time reported in each iTRAK update vs. when the Shuttle Tracker records them
- Updates per minute/hour
- Errors connecting to the iTRAK endpoint

**Comment by kochman** [comment]
These would probably better as Prometheus metrics.

**Comment by evanlazaro** [comment]
Closing per last comment in https://github.com/wtg/shuttletracker/pull/168 - challenges with usefulness and maintainability
