### ISSUE TITLE
Can't add stops to routes through admin interface

### ISSUE THREAD

**Issue by garoller** [wtg/shuttletracker#157]
After creating a stop, when trying to update it (enabling it and assigning a route), an internal server error occurs.

Steps to reproduce:
1. Create a stop
2. Check `enabled` and assign stop to a route
3. Update stop

Expected result: Stop is updated successfully with appropriate information.
Actual result: 500 Internal Server Error

**Comment by evanlazaro** [comment]
No longer relevant due to new admin interface
