### ISSUE TITLE
Routes without stops don't show up on the front end

### ISSUE THREAD

**Issue by garoller** [wtg/shuttletracker#158]
After creating a route, it does not show up on the front end if there are no stops on that route.

Steps to reproduce:
1. Create a route in the admin interface
2. Go to the shuttle tracker interface

Expected result: a route shows up on the front end of the shuttle tracker
Actual result: no route shows up if there aren't any stops on that route

**Comment by kochman** [comment]
This was a problem with one person’s database and isn’t a wider issue.
