### ISSUE TITLE
Map icons and shuttle stats/details

### ISSUE THREAD

**Issue by gbprz** [wtg/shuttletracker#16]
Replace default markers with a shuttle icon and rotate this icon based on the direction this shuttle is heading. Also, add dialog boxes to give detailed shuttle information.

**Comment by gbprz** [comment]
This package seems like a strong candidate for image rotation:
https://godoc.org/code.google.com/p/graphics-go/graphics#RotateOptions

**Comment by kench** [comment]
Shouldn't image rotation be done in CSS/JS?

**Comment by gbprz** [comment]
I was going off the implementation of the original shuttle tracker, but I think there is an option for rotation if your image is an svg in the maps API. Maybe I'll look into that as well.

**Comment by gbprz** [comment]
#29 is related
