### ISSUE TITLE
Alert message

### ISSUE THREAD

**Issue by gbprz** [wtg/shuttletracker#17]
As requested by RPI Parking & Transportation, adding an alert flash message to the fullscreen map view would be useful for inclement weather or other route changes.

**Comment by kench** [comment]
Interested in picking this one up.

Note: The GTFS-realtime specification has some neat definitions of alert types that we could use.

https://developers.google.com/transit/gtfs-realtime/reference#term-definitions

**Comment by kochman** [comment]
Resolved in #126.
