### ISSUE TITLE
Vehicle message times are incorrect

### ISSUE THREAD

**Issue by garoller** [wtg/shuttletracker#181]
When clicking on a shuttle, the pop up message displays the incorrect time. 

For example:

![wrong_time](https://user-images.githubusercontent.com/22043215/47689830-fdeae180-dbc1-11e8-9ff2-718db885bc6a.png)

It seems like the time isn't being updated.

A few minutes later the time updated is the same:

![wrong_time2](https://user-images.githubusercontent.com/22043215/47690194-7b632180-dbc3-11e8-861a-2b4305425500.png)

When you look at https://shuttles.rpi.edu/vehicles, the `created` and `updated` fields are the same time:

![updated_time](https://user-images.githubusercontent.com/22043215/47690224-959cff80-dbc3-11e8-8b2f-d54850d7c1ec.png)

**Comment by kochman** [comment]
I believe this is fixed in #179.

**Comment by kochman** [comment]
resolved
