### ISSUE TITLE
Weekend/Late night routes not bound to a stop

### ISSUE THREAD

**Issue by CoreyBuckley** [wtg/shuttletracker#214]
When I look at [shuttletracker](https://shuttles.rpi.edu/) none of the stops that seem to be on the weekend/late night route actually display that route in their leaflet.

Is this a DB issue? All stops should show the active routes they're bound to. Shouldn't late night be marked as active and being displayed on the stops?

![latenight](https://user-images.githubusercontent.com/28029704/54483581-cd7fa900-482b-11e9-8d7f-917082d39d43.PNG)

**Comment by kochman** [comment]
Yeah, this is a matter of associating the stops with the route. We'll also need to add some new stops since many of them on this route haven't been created yet. It'll be easier after #212 lands.
