### ISSUE TITLE
Developer Guide Page

### ISSUE THREAD

**Issue by evanlazaro** [wtg/shuttletracker#236]
The [Developer Guide page](https://github.com/wtg/shuttletracker/wiki/Developer-Guide) on the Wiki needs to be worked on. See the [petitions developer guide](https://github.com/wtg/petitions-rewrite/wiki/Developer-Guide) for an example.

**Comment by ROBINDEBKL** [comment]
the page https://github.com/wtg/shuttletracker/wiki/Developer-Guide is updated.
