### ISSUE TITLE
Database Schema Page

### ISSUE THREAD

**Issue by evanlazaro** [wtg/shuttletracker#237]
The [Developer Guide page](https://github.com/wtg/shuttletracker/wiki/Database-Schema) on the Wiki needs to be worked on. 

For the first section, use a database visualization tool (such as https://dbdiagram.io/d, there are many out there) to create a graphic for all the tables.

In the section section, describe the meaning of each column for each table and the possible values it could hold.

See the [petitions database page](https://github.com/wtg/petitions-rewrite/wiki/Database-mockup) for an example.

**Comment by beshaz** [comment]
The database schema page is complete!
