### ISSUE TITLE
Docker Setup Instructions Page

### ISSUE THREAD

**Issue by evanlazaro** [wtg/shuttletracker#239]
Per the suggestion in class, a [Docker setup instructions](https://github.com/wtg/shuttletracker/wiki/Docker-Setup-Instructions) page could be helpful as a way to set up the project on all platforms.

We already have a [Dockerfile](https://github.com/wtg/shuttletracker/blob/master/Dockerfile), we just need instructions on downloading docker, setting up the postgres image, and then running the dockerfile.

Docker setup instructions can be borrowed (with credit) from the [YACS documentation](https://yacs.io/#/contributors/installing_docker)

**Comment by beshaz** [comment]
The Docker setup instructions page is now live!
