### ISSUE TITLE
Show which route a shuttle is on

### ISSUE THREAD

**Issue by kochman** [wtg/shuttletracker#59]
The route that a shuttle is on should be obvious in the UI. We got most of the way there at the end of last semester. We just have to link it up to the API so it can be displayed in the UI.

Additionally, we need the late-night shuttle route added so that we can properly associate its shuttles with the correct route.

**Comment by jlyon1** [comment]
This feature is being added in #84

**Comment by kochman** [comment]
Resolved with #84.
