### ISSUE TITLE
Incorrect bus travel speed timestamp

### ISSUE THREAD

**Issue by KeyboardNerd** [wtg/shuttletracker#60]
I'm using https://shuttles.rpi.edu/ and find that the pop-up window of running shuttle contains incorrect bus travel speed timestamp.

e.g.
Bus 97
Traveling East at
20.1 mph as of **8:18:00pm**

Where the time should be **4:18pm**.
My guess is that the timestamp is UTC instead of localized timestamp.

**Comment by kochman** [comment]
Thanks @KeyboardNerd!
