### ISSUE TITLE
Inactive shuttles still displayed

### ISSUE THREAD

**Issue by kochman** [wtg/shuttletracker#62]
Shuttles have an "active" flag. If it is set to false, they're still included in the `/updates` endpoint, which is wrong.

**Comment by KeyboardNerd** [comment]
Hi, I find that Vehicle struct is not even used in updater and database but used in api, which means that the active flag is not relevant to updates. ( really weird though )

**Comment by kochman** [comment]
@garoller I reworked the updates handler in `api/vehicles.go` and changed the `active` field to `enabled` on the model in #98. I'm sorry for stepping on your toes here; there were issues with shuttles not showing up when they should!

**Comment by garoller** [comment]
@kochman No worries, thanks for letting me know!
