### ISSUE TITLE
Route should be displayed in shuttle message

### ISSUE THREAD

**Issue by kochman** [wtg/shuttletracker#86]
The route that we think a shuttle is on should be displayed in the info box that pops up when the user clicks on a shuttle. The data is already there and used to change the colors of the shuttle icons.

Additionally, this might be a good opportunity to stop generating the info box messages on the server and let the client take care of it.

**Comment by JCBird1012** [comment]
Part of this issue is done in #90. 

I haven't offloaded the generation of infoboxes on the server to the client quite yet. I think that would involve a little bit more work; I'd make that a separate issue.

**Comment by CoreyBuckley** [comment]
I'm pretty sure this issue has been resolved and should be closed. See #206

**Comment by kochman** [comment]
Yep!
